### PR TITLE
Strip spaces from resources (fixes #148)

### LINKED ISSUE #148: Strip spaces from resources
Would allow to transform this kind of things:

```
kinto::app::signer_resources_blocklists_certificates = staging/certificates;blocklists-preview/certificates;blocklists/certificates
kinto::app::signer_resources_blocklists_addons = staging/addons;blocklists-preview/addons;blocklists/addons
kinto::app::signer_resources_blocklists_plugins = staging/plugins;blocklists-preview/plugins;blocklists/plugins
kinto::app::signer_resources_blocklists_gfx = staging/gfx;blocklists-preview/gfx;blocklists/gfx
kinto::app::signer_resources_blocklists_qa = staging/qa;blocklists-preview/qa;blocklists/qa
kinto::app::signer_resources_pinning_pins = pinning-staging/pins;pinning-preview/pins;pinning/pins
kinto::app::signer_resources_fennec_catalog = fennec-staging/catalog;fennec-preview/catalog;fennec/catalog
kinto::app::signer_resources_fennec_experiments = fennec-staging/experiments;fennec-preview/experiments;fennec/experiments
```

into something like:

```
kinto::app::signer_resources_blocklists_certificates = staging/certificates      ; blocklists-preview/certificates ; blocklists/certificates
kinto::app::signer_resources_blocklists_addons =       staging/addons            ; blocklists-preview/addons       ; blocklists/addons
kinto::app::signer_resources_blocklists_plugins =      staging/plugins           ; blocklists-preview/plugins      ; blocklists/plugins
kinto::app::signer_resources_blocklists_gfx =          staging/gfx               ; blocklists-preview/gfx          ; blocklists/gfx
kinto::app::signer_resources_blocklists_qa =           staging/qa                ; blocklists-preview/qa           ; blocklists/qa
kinto::app::signer_resources_pinning_pins =            pinning-staging/pins      ; pinning-preview/pins            ; pinning/pins
kinto::app::signer_resources_fennec_catalog =          fennec-staging/catalog    ; fennec-preview/catalog          ; fennec/catalog
kinto::app::signer_resources_fennec_experiments =      fennec-staging/experiments; fennec-preview/experiments      ; fennec/experiments
```

### PR DESCRIPTION
**Pull request by leplatrem**
Fixes #148

### CODE REVIEW

**Comment by leplatrem** [comment]
I like the fact that the resource settings are a lot easier to read

Le 2 mars 2018 15:29, "Ethan Glasser-Camp" <notifications@github.com> a
écrit :

**Comment by glasserc** [comment]
I don't find it easier to read. Instead of seeing three things, my eye sees six things, and I just have to know that some of them are joined together by virtue of being on a line.

**Comment by leplatrem** [comment]
> my eye sees six things

Should we get rid of the colons maybe?

**Comment by glasserc** [comment]
Hmm, maybe, or maybe something more indicative of a relationship? I'd suggest a colon `:` instead of a semicolon, that would be sort of JSON-y, but that wouldn't work very well for stage -> preview -> signed. Maybe `->`? Or is that too cutesy?

**Comment by leplatrem** [comment]
> Maybe `->`? Or is that too cutesy?

Funny, I had suggested `=>` in https://github.com/Kinto/kinto-signer/issues/88#issuecomment-250467171

Why not then, let's go with `->`. It's super easy (we'll strip it anyway)

**Pull request merged**
